name: Deploy to server

on:
  workflow_dispatch:

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: SFTP uploader
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: 'sftp.block15.dreamhost.com'
          username: 'dh_pc4gaj'
          password: ${{ secrets.SERVER_PASSWORD }}
          localDir: '.'
          remoteDir: '/home/dh_pc4gaj/ludjan.com'

