name: Deploy
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: environment
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy to ${{ GITHUB.ENVIRONMENT }}"
    steps:
      - name: "Deploying"
        run: "echo Deployed to production"
  
