name: Deploy to Production
on: 
  workflow_dispatch:
    
jobs:
  setup: 
    name: Setup for deployment
    runs-on: ubuntu-latest
    steps: 
      - run: "echo setup for deployment"
  deploy:
    needs: setup
    name: Deploy
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - run: "echo user=${{vars.USER}}"
      - run: "echo secret=${{secrets.SECRET}}"
  
