name: Deploy
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: environment
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy to production"
        run: "echo user=${{ GITHUB.VARS.PROD_USER }}"
  
