name: Deploy to server

on:
  workflow_dispatch:

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: FTP Deployer
        # You may pin to the exact commit or the version.
        # uses: sand4rt/ftp-deployer@b0fc0a8e0336dddf2192e4415062ad00bd533cba
        uses: sand4rt/ftp-deployer@v1.7
        with:
          # SFTP on
          sftp: true
          # FTP host URL like: ftp.host.com or sftp.host.com
          host: sftp.block15.dreamhost.com
          # FTP port
          # port: # optional, default is 21
          # Ftp username
          username: dh_pc4gaj
          # Ftp password
          password: ${{ secrets.server_password }}
          # The remote folder location of your FTP server
          remote_folder: "ludjan.com"
          # The local folder location
          #local_folder: # optional, default is dist
          # Remove existing files inside FTP remote folder
          #cleanup: # optional
          # includes
          #include: # optional
          # exclude
          #exclude: # optional
          # passive
          #passive: # optional
