name: Deploy
on: 
  workflow_dispatch:
    
jobs:
  deploy:
    name: Deploy
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy to production"
        run: "echo user=${{vars.USER}}"
  
