name: Deploy
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: environment
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy to ${{ github.event.inputs.environment }}"
        run: "echo Deployed to ${{ github.event.inputs.environment }}"
  
