name: "Main"

on: 
  push: 
    branches: [main]
    paths-ignore: 
      - "doc/**"
      - ".github/**"
  workflow_dispatch:

jobs:
  linelint:
    runs-on: ubuntu-latest
    name: Check if all files end in newline
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Linelint
        uses: fernandrone/linelint@0.0.4
        id: linelint
  build:
    needs: linelint
    name: "Building and testing"
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 19
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Build
        run: "javac *.java"
      - name: Test
        run: "java Application.java test"
      
